### ISSUE TITLE
Add OG-tags

### ISSUE THREAD

**Issue by haassie** [haassie/t3ext-core-seo#4]
Add option to set separate title, description and image when shared on Facebook (and other OG-tag based social networks)

**Comment by georgringer** [comment]
What about starting with twitter + facebook and others could be done by 3rd party ext?

**Comment by haassie** [comment]
I think when you do OG-tags for Facebook you already have (almost) all networks using OG-tags. So focussing on Facebook in this issue and Twitter on the other hand in issue #5 will be just fine indeed.
